### PR TITLE
create incident and base router

### PR DESCRIPTION
**Pull request by gurpreetatwal**

### CODE REVIEW

**Comment by motching** [comment]
* I don't quite understand yet how the routes work together, if we receive "GET /", do we answer "Hello World" or the result of Incident.query(); ? Do we have an explicit order for evaluating? If not, should we have something like "GET /incidents/" ? 
  * at incident.post route, should we implement user-facing error handling? Maybe we can swallow the error and just log it. I can't think of much reason for the write to fail unless the DB is completely down, from the frontend the data is validated and well-formatted, supposedly. But if it's easy we could send back "Hey something failed", then we can make an error popup or something.
  * is there a current use case for incident.patch? Interesting question if the users should be able to see / edit their own submissions (later)
  * typos: "kenx", "validationErorHandler"

I am sure I wouldn't catch more subtle bugs in this code yet, I'll play with it in the upcoming days. If this PR is blocking your work, feel free to merge it after answering my questions, it works after all. Thanks, I think we're looking good!

**Comment by gurpreetatwal** [comment]
So there's a bit of magic in how the routers are set up. The way it works is that only the router defined in `routes/index.js` is mounted in the app. 

https://github.com/motching/traffic-counter/blob/ebffc69ed0629e7aa4d6f7838d46f3cbb1a9e34e/backend/index.js#L9-L17

The way the rest of the routers are mounted are through some magic in `routes/index.js`.

https://github.com/motching/traffic-counter/blob/ebffc69ed0629e7aa4d6f7838d46f3cbb1a9e34e/backend/routes/index.js#L16-L25

What the code above does is:
1. get a list of the files in the `routes` directory
2. filter out any files that don't end in `.js` or are named `index.js`
3. `require` in each file and get the name of the file not including the the `.js` part
4. Use the main export of the required'd file (which should be a router) and mount that export as the code that should handle all requests to `/<name-of-file>`

This PR sets up the following routes:
- [`GET /`](https://github.com/motching/traffic-counter/blob/ebffc69ed0629e7aa4d6f7838d46f3cbb1a9e34e/backend/routes/index.js#L11)
- [`GET /incident`](https://github.com/motching/traffic-counter/blob/ebffc69ed0629e7aa4d6f7838d46f3cbb1a9e34e/backend/routes/incident.js#L17)
- [`POST /incident/`](https://github.com/motching/traffic-counter/blob/ebffc69ed0629e7aa4d6f7838d46f3cbb1a9e34e/backend/routes/incident.js#L21)
- [`POST /incident/:id`](https://github.com/motching/traffic-counter/blob/ebffc69ed0629e7aa4d6f7838d46f3cbb1a9e34e/backend/routes/incident.js#L25)
- [`PATCH /incident/:id`](https://github.com/motching/traffic-counter/blob/ebffc69ed0629e7aa4d6f7838d46f3cbb1a9e34e/backend/routes/incident.js#L29)

**Comment by gurpreetatwal** [comment]
As for the second concern, there is error handling, it's just handled in a separate middleware. Since we're using an Objection.js model, that has a defined schema, all the data is validated before it is inserted into the database. If there is some error, the insert call throws a `Objection.ValidationError. That error is handled by:

 https://github.com/motching/traffic-counter/blob/ebffc69ed0629e7aa4d6f7838d46f3cbb1a9e34e/backend/lib/middleware.js#L13-L31

This middleware is mounted prior to all the routers in index.js:

https://github.com/motching/traffic-counter/blob/ebffc69ed0629e7aa4d6f7838d46f3cbb1a9e34e/backend/index.js#L14-L17

So every request first passes through `serve`, then `validationErrorHandler` and then the router.

Take a look at https://github.com/koajs/koa/blob/master/docs/guide.md#writing-middleware for a much better explanation of the order in which the middleware are executed

**Comment by gurpreetatwal** [comment]
I don't currently forsee any reason for PATCH incident, but left it there for a completeness. Left it as a todo so we can revisit later if need by

**Comment by motching** [comment]
Thanks for explaining! Merging now.

**Pull request merged**
